### ISSUE TITLE
Jacoby6000 nomination

### ISSUE THREAD

**Issue by edmundnoble** [tonymorris/do-not-hire#7]
Gaslighting me on how github is supposed to work (PRs to forks are the correct way to do collaboration, duh)

**Comment by Jacoby6000** [comment]
U fokin wot m8?

**Comment by Jacoby6000** [comment]
I propose a new rule.

Unhirables are not allowed to nominate unhirables.

**Comment by edmundnoble** [comment]
Tony's maintaining the list, so that's hypocritical (offense number 2 for you)

**Comment by Jacoby6000** [comment]
BRB while I clone all of the work y'all have put together so I can use a copy of this repository as evidence for my new business' credibility.

**Comment by edmundnoble** [comment]
Fixed.
